on:
    push:
        branches:
            - main

jobs:
    ping_server:
        runs-on: ubuntu-20.04
        steps:
          - name: Ping the web service URL
            uses: jtalk/url-health-check-action@v4
            with:
                url: https://full-stack-open-pokedex-pupa.onrender.com/