on:
    schedule:
        - cron: '0 0 * * *'

jobs:
    ping_server:
        runs-on: ubuntu-20.04
        steps:
          - name: Check the web service URL
            uses: jtalk/url-health-check-action@v4
            with:
                url: https://full-stack-open-pokedex-pupa.onrender.com/